### ISSUE TITLE
About the minmax value

### ISSUE THREAD

**Issue by pray5959** [cchen-cc/SIFA#11]
Hi,thanks for your work. Are the minmax values in data_loder.py  the statistics of enhanced tfrecords or  processed nii? Or they are just the same. And if the  test dataset is taken into consideration?

**Comment by cchen-cc** [comment]
Hi, those are statistics of the tfrecords not including the test dataset as we want to hold out the test dataset from any training procedure.

**Comment by pray5959** [comment]
@cchen-cc  Thanks!
