### ISSUE TITLE
about the data

### ISSUE THREAD

**Issue by Liu-stack-2021** [cchen-cc/SIFA#12]
Hi, thank you for your work. Can you send the pre-processed data again? The previous link cannot be clicked in, thank you.

**Comment by cchen-cc** [comment]
Hi, I just checked the link and had no problem clicking in. 
Those links direct to google drive folders. 
Maybe you are having problems accessing google drive?

**Comment by Liu-stack-2021** [comment]
Hello, I have some problems accessing the Google driver. If possible, could you please send the data to my mailbox? I am looking forward to your reply.Email address: lh2019@smail.hunnu.edu.cn
