### ISSUE TITLE
evaluate question

### ISSUE THREAD

**Issue by yfpchen** [cchen-cc/SIFA#14]
Do you use the.nii data set directly in your evaluation.py?Looking forward to your reply

**Comment by cchen-cc** [comment]
We use .npz files in the evaluate.py. 
To convert .nii data to .npz, the script savenpz.py under utils folder can be used.

**Comment by yfpchen** [comment]
Thank you for your answer. The result I get is the value of Dice and Assd, but the result of image segmentation is not obtained. I am looking forward to your reply again

**Comment by cchen-cc** [comment]
You can save the segmentation prediction tmp_pred into file.

**Comment by yfpchen** [comment]
Can you provide the code? thank you

**Comment by yfpchen** [comment]
Should I save it as an array and then convert it to an image

**Comment by cchen-cc** [comment]
You can save it into any format you like.

**Comment by cchen-cc** [comment]
tmp_pred is a 3D volume. You can slice it and save each slice into images with function such as matplotlib.pyplot.imsave (there are many options).

**Comment by yfpchen** [comment]
First of all, thank you for your reply, but I still have the following problems. I will use the following code (np.save ('/liu/SIFA-master/SIFA-master/pre_output/arraytest.npy',tmp_pred)) to save tmp_pred as .npy format and convert it into 256 slice images.Why did I put 4 samples (CT_1003, CT_1008, CT_1014 and CT_1019) into my test data set, and only a 256*256*256 volume result after using the above save code? Is the result of tmp_pred a 3D volume or four 3D volumes? Looking forward to your reply

**Comment by cchen-cc** [comment]
tmp_pred contains one 3D volume.

**Comment by Halleyawoo** [comment]
@yfpchen Hi！How to get the txt file of TESTFILE_FID in the evaluate.py file ？
Thx！
