### ISSUE TITLE
MRI testing slices in the train&val folder

### ISSUE THREAD

**Issue by zlheui** [cchen-cc/SIFA#16]
Dear authors,

It is of great pleasure to read your recent paper "Unsupervised Bidirectional Cross-Modality Adaptation via Deeply Synergistic Image and Feature Alignment for Medical Image Segmentation". And thanks for sharing the code and the data to the public.

In your release of the data from PnpAda_release_data.zip. The MRI testing data is also preprocessed and included in the train&val folder, where there is 9600 slices for training and 2400 slices for validation. If we want to conduct domain adaptation in the direction from CT to MRI, how can we remove testing slices among these 12000 slices for MRI data? As you mentioned in the paper, "For both applications, each modality was randomly split with 80% scans for training and 20% scans for testing", so we should not use the MRI testing slices for training the network. But currently, there is no easy way to remove the testing MRI slices, as the name of the slices is as "mr_train_slicexxxx.tfrecords", we cannot remove the testing slices based on the file names. Is it possible for you to provide the train&val slices of MRI data, when MRI data is used as the target domain. In addition, could you also provide the updated minmax value for the MRI data when testing slices are removed. Currently the minmax value is -1.8 to 4.4 for MRI data, after removing the test slices, will these values change?

Thanks very much.

**Comment by cchen-cc** [comment]
Hi,

Actually the 9600 slices are the "80% scans for training" mentioned in the paper and the rest 2400 slices are generated from the 20% scans for testing and are not used during training. 

The current statistics were calculated based on the 9600 slices of training data and no need to change of you use the same data.

**Comment by zlheui** [comment]
okay, got it. Thanks very much.

**Comment by chke097** [comment]
@zlheui     Hello, may I ask how you solved this problem? I still don't understand how to choose these training sets and verification sets. Could you share the solution with me? Thank you!
