### ISSUE TITLE
Problem with gettfrecords.py - Files can't be loaded by Tensorflow

### ISSUE THREAD

**Issue by mary-alegro** [cchen-cc/SIFA#18]
Hi!

Thanks for sharing your work. I'm trying to use SIFA with my own dataset but I can't get Tensorflow to read the tfrecord files I generate with gettfrecords.py. I keep getting the following error:

> OutOfRangeError (see above for traceback): RandomShuffleQueue '_4_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 8, current size 0)
> 	 [[node shuffle_batch (defined at /hpc/scratch/nvme1/mar83345/SIFA/data_loader_liver.py:86)  = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]

I generated the data from float32 images and int64 labels. I've checked the file paths inside the txt files and they are correct. Could you share the code you used for generating the original dataset? I'm suspicious there's something wrong with the way the files are being generated right now.

Thanks!!

**Comment by mary-alegro** [comment]
I fixed the problem. I'll put this here since it might be useful for someone else. The comments in data_loader.py gave the impression the label data should be [256,256,1] when, in fact, it has to be [256,256,3].

>      decomp_feature = {
>         # image size, dimensions of 3 consecutive slices
>         'dsize_dim0': tf.FixedLenFeature([], tf.int64), # 256
>         'dsize_dim1': tf.FixedLenFeature([], tf.int64), # 256
>         'dsize_dim2': tf.FixedLenFeature([], tf.int64), # 3
>         # label size, dimension of the middle slice
>         'lsize_dim0': tf.FixedLenFeature([], tf.int64), # 256
>         'lsize_dim1': tf.FixedLenFeature([], tf.int64), # 256
>         'lsize_dim2': tf.FixedLenFeature([], tf.int64), # 1
>         # image slices of size [256, 256, 3]
>         'data_vol': tf.FixedLenFeature([], tf.string),
>         # label slice of size [256, 256, 1]
>         'label_vol': tf.FixedLenFeature([], tf.string)}

Just save you labels as [256,256,3] and it should load fine.

**Comment by cchen-cc** [comment]
Hi, thanks for pointing out this issue. 
I have updated data_loader.py to make it clearer.
