### ISSUE TITLE
hi, do you have the code to transfer data to tfrecord?

### ISSUE THREAD

**Issue by winwinJJiang** [cchen-cc/SIFA#2]
Thanks!!!

**Comment by cchen-cc** [comment]
Hi,

I thought transferring data to tfrecord is easy once the data format of the tfrecord is specified (as shown below). We will release the code later.

decomp_feature = {
%image size, dimensions of 3 consecutive slices
'dsize_dim0': tf.FixedLenFeature([], tf.int64), # 256
'dsize_dim1': tf.FixedLenFeature([], tf.int64), # 256
'dsize_dim2': tf.FixedLenFeature([], tf.int64), # 3
%label size, dimension of the middle slice
'lsize_dim0': tf.FixedLenFeature([], tf.int64), # 256
'lsize_dim1': tf.FixedLenFeature([], tf.int64), # 256
'lsize_dim2': tf.FixedLenFeature([], tf.int64), # 1
%image slices of size [256, 256, 3]
'data_vol': tf.FixedLenFeature([], tf.string),
%label slice of size [256, 256, 1]
'label_vol': tf.FixedLenFeature([], tf.string)
}

**Comment by LUYU0004** [comment]
Hello, I got some more questions about the data conversion.
In the paper and your answer above, it is mentioned that the image slices are cropped into (256,256). However, the **raw** MRI and CT images  from MMWHS2017 dataset are of various shape. For MRI, the shape ranges from (288, 288, 135) to (512, 512, 160). While CT images have shapes ranging from (512, 512, 187) to (512, 512, 363).

May i know in better details that:
(1) How do you crop the raw images of such varied height and width? E.g is it at the center of each raw slice, with the other parts discarded?
(2) How do you handle the varying depth?
(3) For _decode_samples(image_list, shuffle=False) function in "data_loader.py", if **only the central slice** is need for %image slices of size [256, 256, 3], then why do you store it as 3 consecutive slices in tfrecords?

Thank you very much!

**Comment by cchen-cc** [comment]
Hi,

We first cropped the raw volumes centering at the heart area as the field of view in MRI and CT data is quite different. We then resampled the cropped data into (256, 256). 

We tried earlier to use three adjacent slices as the input, but found out that using single slice gives better results. But we didn't modify the data stored in the tfrecords.

**Comment by LUYU0004** [comment]
May i know what shape will it result in after "cropped the **raw volumes** centering at the heart area as the field of view in MRI and CT data is quite different"? I would really appreciate if you can provide the exact [X,X,X] shape number.

And what is the re-sampling method that you adapted for cropping data into (256, 256)?

Thank you so much for the prompt reply!

**Comment by cchen-cc** [comment]
Hi,

The exact shape varies in each volume. We used the spline interpolation of order 3.

**Comment by LUYU0004** [comment]
Thank you so much for clarifying! It helps a lot for my understanding.
Looking forward to more details in your future released code!

**Comment by Endless-Hao** [comment]
@LUYU0004  Do you solve it? How to use data_loader.py to get tfrecord.

**Comment by LUYU0004** [comment]
Hi,

I have attempted, but yet there are plenty of missing details that i am awaiting for the code that will be released from the author. So the steps below are heavily based on my speculation, please refer to the information provided by the author as final guidelines.

As far as i understand, the **data_loader.py** only loads xx.tfrecord that each store an image and its label (or say a slice of a volume), so you need to download the raw dataset, then build a preprocessor to:

0) split the 20 CT volumes into 16 training 4 evaluation 
1) normalized the volumes (not sure, need author's clarification)
2) "cropped the raw volumes centering at the heart area as the field of view in MRI and CT data" as specified by the author's reply above, resulting in varying shapes
3) convert original integer label to 0-7
4) resample to [256, 256] by cubic interpolation (emm, not sure whether it is resampling 3D directly or 2D)
5) save the corresponding slice of each image and label volumes  into one xx.tfrecord
6) create datalists

Hope that helps!

**Comment by Endless-Hao** [comment]
@LUYU0004  Ok thanks！I also write code to transfer data to TFrecords.

**Comment by Endless-Hao** [comment]
@LUYU0004  Did the author tell about  window width and window level？When we train or test,do we need them?

**Comment by cchen-cc** [comment]
A new file gettfrecords.py has been uploaded to write data into .tfrecords.
