### ISSUE TITLE
source image and target image

### ISSUE THREAD

**Issue by lfxuan** [cchen-cc/SIFA#24]
Thank you very much for your work! During the research process, I have a question. In the thesis, TABLE1 Cradiac MRI-CT means that MRI is used as the source image during training and CT is used as the target image? And Cradiac CT-MRI is the opposite? Looking forward to your reply!

**Comment by cchen-cc** [comment]
Yes, you are right.

**Comment by Halleyawoo** [comment]
@lfxuan my evaluation results is very low. What about yours? I didn't change anything about the author's experimental setup

**Comment by lfxuan** [comment]
@Halleyawoo I changed the batch_size, and the predicted results are similar to those of the paper.

**Comment by Halleyawoo** [comment]
@lfxuan Thanks a lot！

**Comment by Sydhm** [comment]
@lfxuan Hi there, could I ask what is the batch_size for your training? And also what results did you get for your best checkpoint? I couldn't seem to find the best checkpoint that matches the author's reporting performance.
