### ISSUE TITLE
How to easily implement multi-GPU parallel operation？

### ISSUE THREAD

**Issue by Halleyawoo** [cchen-cc/SIFA#25]
I saw the method of using multiple graphics cards in parallel in this [link,](https://github.com/tensorflow/tensorflow/blob/r0.12/tensorflow/models/image/cifar10/cifar10_multi_gpu_train.py) but it is a bit complicated to change it. I wonder if there is a simpler method?

**Comment by cchen-cc** [comment]
We didn't try to implement multi-GPU on this project. 
I'm gonna close this issue as it's not related to the released code.

**Comment by Halleyawoo** [comment]
Thx
