### ISSUE TITLE
evaluate problem

### ISSUE THREAD

**Issue by Halleyawoo** [cchen-cc/SIFA#27]
Hello author, I read the previous issue, but it did not solve my problem. When running the evaluate.py code, the adaptation of the CT image was correct, but when adapting to the MR image, the following error occurred:
RuntimeError: The first supplied array does not contain any binary object.

Traceback (most recent call last):
  File "evaluate.py", line 253, in <module>
    main(config_filename='/media/nomachine/project/SIFA-master/config_param.json')
  File "evaluate.py", line 248, in main
    sifa_model.test()
  File "evaluate.py", line 215, in test
    assd_list.append(mmb.assd(pred_test_data_tr, pred_gt_data_tr))
  File "/home/hfcui/.local/lib/python2.7/site-packages/medpy/metric/binary.py", line 453, in assd
    assd = numpy.mean( (asd(result, reference, voxelspacing, connectivity), asd(reference, result, voxelspacing, connectivity)) )
  File "/home/hfcui/.local/lib/python2.7/site-packages/medpy/metric/binary.py", line 561, in asd
    sds = __surface_distances(result, reference, voxelspacing, connectivity)
  File "/home/hfcui/.local/lib/python2.7/site-packages/medpy/metric/binary.py", line 1213, in __surface_distances
    raise RuntimeError('The first supplied array does not contain any binary object.')
RuntimeError: The first supplied array does not contain any binary object.

**Comment by Halleyawoo** [comment]
I don’t know if it’s the MR test file. The MR test file is much smaller than the compressed package of the CT test file.

**Comment by Halleyawoo** [comment]
I don’t know if it’s the problem with the MR test file

**Comment by Halleyawoo** [comment]
Model training 20000 will report an error, the model trained 3000 times is not wrong, why?

**Comment by cchen-cc** [comment]
From reading the error, it says that the first supplied array does not contain any binary object. It indicates that the predictions are all zeros for all the locations. You may want to check whether there are some problems in the training after the adaptation direction is changed. 

It is difficult to debug from my side without knowing more details about what you did when adapting to the MR images.

**Comment by Real-YeJ** [comment]
@Halleyawoo hey, I meet a same problem, do you know how to solve it?

**Comment by Crescentz** [comment]
The same problem, do you know how to solve it?

**Comment by Halleyawoo** [comment]
> The same problem, do you know how to solve it?

I just changed the training epoches, solved.

**Comment by Halleyawoo** [comment]
> @Halleyawoo hey, I meet a same problem, do you know how to solve it?

I just changed the training epoches, solved.

**Comment by Crescentz** [comment]
your "max_step"  is ?

**Comment by Halleyawoo** [comment]
> your "max_step" is ?

epoch 15000
batch 4
1 1080Ti

**Comment by wangm-ting** [comment]
When I transfer from mrtoct,it occured.How to solve it?
