### ISSUE TITLE
question about data in train and evaluation 

### ISSUE THREAD

**Issue by Real-YeJ** [cchen-cc/SIFA#29]
hey, author, thanks for great work.  I have some questions about data in train and evaluation. when training, each tfrecords file only has three slices, right?  that is to say,  we regard a tfrecords as an image. when evaluating, it seems that you use .npz file in evaluate.py, so does each .npz file save three slices as well?

**Comment by cchen-cc** [comment]
During data preprocessing, three consecutive slices are saved in one tfrecords, but during training, only the middle slice is used.
When evaluating, one .nii file containing hundreds of slices in one CT/MR volume was converted into .npz format to input into evaluate.py.

**Comment by Real-YeJ** [comment]
@cchen-cc thanks !
