### ISSUE TITLE
About create_datalist.py

### ISSUE THREAD

**Issue by Halleyawoo** [cchen-cc/SIFA#30]
Hello author, when I ran create_datalist.py, I found that after commenting out the np.random.shuffle(filename_all) code, the order of the generated txt files is still chaotic. What is it?
During the training and verification, I generated the txt file for training verification. The order is chaotic, and the test results are different from the test results in the normal order. I don’t know which order is the correct result, so what should I do? Which order should be used?

**Comment by cchen-cc** [comment]
To make the order consistent, you may want to add filename_all.sort() before np.random.shuffle().
Order should not affect the results much. For the evaluation, if the model parameters are the same, no matter which order is used to evaluate the files, the same results should be obtained.
