### ISSUE TITLE
Visualized slices of the segmentation results shown in the paper

### ISSUE THREAD

**Issue by lfxuan** [cchen-cc/SIFA#31]
Hello, thank you very much for your work! Which slice is the visualization result of MR and CT shown in Figure 3 of the paper? Looking forward to your reply!

**Comment by cchen-cc** [comment]
Here are the test case ids and slice numbers:
CT: '1003': slice 140, '1014': slice 77.
MR:'1009': slice 50, '1019': slice 83.

**Comment by lfxuan** [comment]
Thanks a lot!
