### ISSUE TITLE
Keep rate value

### ISSUE THREAD

**Issue by Sydhm** [cchen-cc/SIFA#35]
Hi, the keep rate value across the whole programme seems to be 1.0. That leaves all the general_conv2d blocks to have all elements of weight to be zero. Is that correct?

**Comment by cchen-cc** [comment]
Keep rate to be 1.0 means that no dropout is used, so all elements of weight should be one.

**Comment by Sydhm** [comment]
> Keep rate to be 1.0 means that no dropout is used, so all elements of weight should be one.

I see that you are referring to a tensorflow v1.15 function while v2.4 has different arguments definition now. Thank you for the reply!
