### ISSUE TITLE
MR Cardiac testing Dataset broken google drive link

### ISSUE THREAD

**Issue by muddasser-mm** [cchen-cc/SIFA#37]
Hello @cchen-cc . I'm currently testing your github implementation of SIFT using the cardiac dataset. The links to which you have shared in the github page. I could test the CT data (shared as .nii in test_ct_image&labels) with your trained models, which you have also shared (Thanks for that). But, the google drive link for MR testing dataset is broken and I wanted to know if it's possible to share that dataset. Thanks in advance.

**Comment by cchen-cc** [comment]
Hi, I have updated the google drive link for MR testing dataset. Let me know if any further problem.

**Comment by muddasser-mm** [comment]
Hello @cchen-cc. Thank you very much for the updated link. In the previous issue #34 you have mentioned the training and testing volumes you used for abdomen. I wanted to know if the abdomen pre-processed training and testing data is also readily available and possible for you share. This, since I needed it for quick testing. But, otherwise no problem I'll try pre-processing it from the raw dataset.

**Comment by cchen-cc** [comment]
Hi @muddasser27 I don't think I can share the data without the permission from the data organizers. Sorry about that.

**Comment by muddasser-mm** [comment]
Hi @cchen-cc. Thank you for response. No problem.
