### ISSUE TITLE
pred_mask_a and pred_mask_b

### ISSUE THREAD

**Issue by manigalati** [cchen-cc/SIFA#38]
Hello! :)

Just a quick doubt I have on the code: is it normal that in the file "model.py" at row 81 it is returned pred_mask_b where it should go pred_mask_a?

Thanks in advance!

**Comment by manigalati** [comment]
To be more precise, I don't see why you gave two names to the same thing ('pred_mask_a' and 'pred_mask_b' to pred_mask_b and 'pred_mask_fake_a' and 'pred_mask_fake_b' to pred_mask_fake_b). This makes me a little confused since I am trying to distinguish at training the segmentation masks of the images coming from the source domain and from the target domain. My guess is that outputs['pred_mask_b'] are the predictions for the data coming from the target domain, outputs['pred_mask_fake_b'] are the predictions for the data coming from the source domain, and I could use indifferently '_b' or '_a' in both the cases. Are my suppositions correct?

**Comment by cchen-cc** [comment]
Hi, the pred_mask_a in row 81 is actually not used and the variable pred_mask_a is not defined in model.py, so I just passed pred_mask_b to it. This is something missed during code update/modification. I should have just removed pred_mask_a.

**Comment by manigalati** [comment]
Thank you for the clarification! :) So, should I use outputs['pred_mask_fake_b'] in order to refer to the segmentation masks of the images coming from the source domain?

**Comment by cchen-cc** [comment]
Yes. Actually in the code outputs['pred_mask_fake_b']: pred_mask_fake_b indeed refers to the segmentation masks of source images. The input/output flow is images_a -> fake_images_b -> latent_fake_b -> pred_mask_fake_b.
