### ISSUE TITLE
Train problem

### ISSUE THREAD

**Issue by Endless-Hao** [cchen-cc/SIFA#4]
Hi, I met a strange problem. When I was training using your example data before, I was no problem. When I was training using my own data, I was wrong. I use you 'gettfrecords.py' to get training data.
Error blow:
OutOfRangeError (see above for traceback): RandomShuffleQueue '_2_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 8, current size 0)
	 [[{{node shuffle_batch}} = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
 Were there any detail about get data?I don't know how to fix it.
Thanks!

**Comment by Endless-Hao** [comment]
@cchen-cc  i fix it.Thanks！

**Comment by Endless-Hao** [comment]
@cchen-cc Hi，Wish you upload testing code.Thanks!

**Comment by cchen-cc** [comment]
The testing code has been uploaded.

**Comment by lfxuan** [comment]
Hello ! I encountered the same problem during training, how did you solve this problem?

**Comment by tianbao-li** [comment]
> @cchen-cc i fix it.Thanks！

Hello ! I met the same problem, how did you solve this problem? Looking forward for your reply!
