### ISSUE TITLE
Cardiac data ct2mr giving poor results

### ISSUE THREAD

**Issue by muddasser-mm** [cchen-cc/SIFA#40]
Hello @cchen-cc. I tried training the SIFA network from scratch based on the code exactly as in this github on the exact same data you are using (which you have also provided). For mr2ct I get equivalent dice score of 73.8 on exact test samples you have used but for ct2mr the performance is very low and I get a best dice score of 54.5 (63.4 in paper) when tested on the exact same samples you have used and provided. The data statistics are unchanged and I ran for same number of iterations 20000. I wanted to know if I'm missing anything or any hints about the same. Thanks in advance.

**Comment by muddasser-mm** [comment]
Issue Solved. The training seems to fluctuate and performance oscillates and dips with more training. But can see better results nearer to that listed in the paper in the overall training process

**Comment by wangm-ting** [comment]
> 问题已解决。随着更多的训练，训练似乎会波动，性能会波动和下降。但是在整个训练过程中可以看到更接近论文中列出的更好的结果

File "evaluate.py", line 200, in test
    assd_list.append(mmb.assd(pred_test_data_tr, pred_gt_data_tr))
  File "/data/xjs/envs/environments/tf1/lib/python3.7/site-packages/medpy/metric/binary.py", line 453, in assd
    assd = numpy.mean( (asd(result, reference, voxelspacing, connectivity), asd(reference, result, voxelspacing, connectivity)) )
  File "/data/xjs/envs/environments/tf1/lib/python3.7/site-packages/medpy/metric/binary.py", line 561, in asd
    sds = __surface_distances(result, reference, voxelspacing, connectivity)
  File "/data/xjs/envs/environments/tf1/lib/python3.7/site-packages/medpy/metric/binary.py", line 1213, in __surface_distances
    raise RuntimeError('The first supplied array does not contain any binary object.')
RuntimeError: The first supplied array does not contain any binary object.

for mr2ct,have you met this problem?

**Comment by chke097** [comment]
@wangm-ting 
Hello, I have the same problem with you. How did you solve it?
