### ISSUE TITLE
Model used for upper bound supervised training in paper

### ISSUE THREAD

**Issue by muddasser-mm** [cchen-cc/SIFA#41]
Hello @cchen-cc. I'm currently testing your github implementation of SIFA using the cardiac dateset. Your paper mentions about the supervised training, which is the upper bound used to compare the performance with. I wanted to know which model was used for this supervised training. If it was the same encoder-decoder used in the SIFA with the segmentation loss or any other network was used with the provided cardiac and abdomen dataset.

**Comment by cchen-cc** [comment]
Hi, it was the same encoder-decoder used in SIFA.

**Comment by muddasser-mm** [comment]
@cchen-cc Thanks for your reply. I wanted to know if the same augmented dataset shared by you, was used for supervised training too?  When I'm using your provided cardiac dataset for supervised learning, I'm getting quite bad results, hence wanted to know about the same.

**Comment by cchen-cc** [comment]
Yes, the same augmented dataset is used for supervised training.

**Comment by muddasser27** [comment]
@cchen-cc thanks for the info. When I implemented the same encoder-segmentor model in PyTorch and trained using the given data, I'm getting bad performance. The network is giving same output for any input in validation. I know it doesn't concern the topic of UDA directly here, but it would be great if you could give any hints if you came across something similar when you used the data.

**Comment by muddasser-mm** [comment]
@cchen-cc, thank you very much for the info.
