### ISSUE TITLE
same image files for ct and mri as the original MMWHS Challenge?

### ISSUE THREAD

**Issue by billhhh** [cchen-cc/SIFA#44]
Thanks for sharing this good work.

May I know if you used the same image files for ct and mri as the original MMWHS Challenge? Seems the .nii files have different sizes than the original files (as shown in the img).

![image](https://user-images.githubusercontent.com/7709725/126092972-a12202b8-1fb7-4ac5-ab11-3d44de0a0ae5.png)

May I know any processes has been performed? Or it is a different dataset?

**Comment by billhhh** [comment]
Also, this repo uses the same slices as Medical-Cross-Modality-Domain-Adaptation ( seems 20 mri all used for training and validation). May I know the mr test in this repo is the external data or processed ones?

Really looking forward to hearing your answer.
Best

**Comment by cchen-cc** [comment]
The data are from MMWHS Challenge, but has some preprocessing. For the CT test volume, we applied resize operation into the raw images, which can be easily seen if you visualize the data shown in your figure.

The MR test data are also from the 20 MRI of MMWHS Challenge.

**Comment by billhhh** [comment]
Hi,
Thanks for your reply. I still have some questions regarding the data since I am trying to follow your work.

1. In the original MMWHS Challenge, there are 20 CT and 20 MR. May I know which IDs of CT and MR are for model training? and which IDs of CT and MR for model validation? May I know which IDs did the MR test data come from as well
2. Is the data splits the same in https://github.com/carrenD/ummkd?

Thank you

**Comment by cchen-cc** [comment]
1. The IDs of test volume have already been indicated in the filenames of released data and the rest of volumes are used for training.
2. You may want to ask at the repo of ummkd.

**Comment by billhhh** [comment]
Thanks for the info. They are helpful
