### ISSUE TITLE
Number of labels and segmentation results

### ISSUE THREAD

**Issue by orhir** [cchen-cc/SIFA#45]
HI,
I have a couple of questions:
1.In the paper you compare your results with CycleGANs results, but as far as I know CycleGAN is not a segmentation network. How was your analysis done?
2. In the original dataset(from the contest) there are 8 labels, but you describe only 4 labels. Did I misunderstood or you disregarded 4 of the labels? How was this analysis done?

Thanks in advance,
Or  Hirschorn.

**Comment by cchen-cc** [comment]
Hi,
1. We first trained a CycleGAN model to translate the image and then used the translated images to train a segmentation network. 
2. We only aimed to segment 4 structures, so the other labels were changed into the background.

**Comment by orhir** [comment]
Thanks for the reply!
