### ISSUE TITLE
数据集预处理

### ISSUE THREAD

**Issue by lanjinraol** [cchen-cc/SIFA#49]
您好～请问Pnp-ada数据集中连续的slice是属于同一个case的么？
例如：ct_train_slice0.tfrecords 至 ct_train_slice599.tfrecords 属于同一个case么？

**Comment by cchen-cc** [comment]
你举的这两个例子，slice0和slice599，不连续啊。.tfrecord的slice应该都经过了randomize处理，不一定属于同一个case。
