### ISSUE TITLE
The testing data of MR

### ISSUE THREAD

**Issue by chinacui** [cchen-cc/SIFA#6]
Hi, Thanks for reading this message. After downloading the data, I found there is the testing data of ct. However, no testing data of MR is provided. Could you give the index of MR for testing? It can help us learn the code from CT to MR adaptation. Thanks.

**Comment by cchen-cc** [comment]
The index of MR for testing is 1007, 1009, 1018, 1019.

**Comment by chinacui** [comment]
Thanks for your quick reply.
