### ISSUE TITLE
assd error

### ISSUE THREAD

**Issue by lfxuan** [cchen-cc/SIFA#7]
Hello ! During the evaluation, why did the following error occur:
File "evaluate.py", line 210, in test
    assd_list.append(mmb.assd(pred_test_data_tr, pred_gt_data_tr))
  File "/anaconda3/envs/sys/lib/python3.6/site-packages/medpy/metric/binary.py", line 453, in assd
    assd = numpy.mean( (asd(result, reference, voxelspacing, connectivity), asd(reference, result, voxelspacing, connectivity)) )
  File "/anaconda3/envs/sys/lib/python3.6/site-packages/medpy/metric/binary.py", line 561, in asd
    sds = __surface_distances(result, reference, voxelspacing, connectivity)
  File "/anaconda3/envs/sys/lib/python3.6/site-packages/medpy/metric/binary.py", line 1213, in __surface_distances
    raise RuntimeError('The first supplied array does not contain any binary object.')
RuntimeError: The first supplied array does not contain any binary object.
srun: error: gpu1: task 0: Exited with exit code 1

**Comment by cchen-cc** [comment]
I've never had such a error. 
It looks like that the prediction volume you gave to the assd function contains all zero values. 
You may want to have a check the element contained in the prediction volume.

**Comment by lfxuan** [comment]
Thank you, you are right！the previous model training has too few steps, resulting in zero results. Now I try to set max_step =10000 to train, but always keep the following error:
Caused by op 'shuffle_batch', defined at:
  File "main.py", line 559, in <module>
    main(config_filename='./config_param.json')
  File "main.py", line 555, in main
    sifa_model.train()
  File "main.py", line 311, in train
    self.inputs = data_loader.load_data(self._source_train_pth, self._target_train_pth, True)
  File "/SIFA-master/data_loader.py", line 96, in load_data
    images_i, images_j, gt_i, gt_j = tf.train.shuffle_batch([image_i, image_j, gt_i, gt_j], BATCH_SIZE, 500, 100)
  File "/anaconda3/envs/sys/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 1300, in shuffle_batch
    name=name)
  File "/anaconda3/envs/sys/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 846, in _shuffle_batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/anaconda3/envs/sys/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 483, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/anaconda3/envs/sys/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3480, in queue_dequeue_many_v2
    component_types=component_types, timeout_ms=timeout_ms, name=name)
  File "/anaconda3/envs/sys/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/anaconda3/envs/sys/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)
  File "/anaconda3/envs/sys/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): RandomShuffleQueue '_4_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 10, current size 6)
	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]

**Comment by cheng-01037** [comment]
Seems that your dataloader is not reading tfrecord files.

**Comment by lfxuan** [comment]
Thanks for your answer！ the problem is solved。

**Comment by Crescentz** [comment]
How to solve 'RuntimeError: The first supplied array does not contain any binary object.

**Comment by chke097** [comment]
> Thank you, you are right！the previous model training has too few steps, resulting in zero results. Now I try to set max_step =10000 to train, but always keep the following error: Caused by op 'shuffle_batch', defined at: File "main.py", line 559, in main(config_filename='./config_param.json') File "main.py", line 555, in main sifa_model.train() File "main.py", line 311, in train self.inputs = data_loader.load_data(self._source_train_pth, self._target_train_pth, True) File "/public/home/jd_yangfeng/lfx/SIFA-master/data_loader.py", line 96, in load_data images_i, images_j, gt_i, gt_j = tf.train.shuffle_batch([image_i, image_j, gt_i, gt_j], BATCH_SIZE, 500, 100) File "/public/home/jd_yangfeng/anaconda3/envs/sys/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 1300, in shuffle_batch name=name) File "/public/home/jd_yangfeng/anaconda3/envs/sys/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 846, in _shuffle_batch dequeued = queue.dequeue_many(batch_size, name=name) File "/public/home/jd_yangfeng/anaconda3/envs/sys/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 483, in dequeue_many self._queue_ref, n=n, component_types=self._dtypes, name=name) File "/public/home/jd_yangfeng/anaconda3/envs/sys/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3480, in queue_dequeue_many_v2 component_types=component_types, timeout_ms=timeout_ms, name=name) File "/public/home/jd_yangfeng/anaconda3/envs/sys/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper op_def=op_def) File "/public/home/jd_yangfeng/anaconda3/envs/sys/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3414, in create_op op_def=op_def) File "/public/home/jd_yangfeng/anaconda3/envs/sys/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1740, in **init** self._traceback = self._graph._extract_stack() # pylint: disable=protected-access
> 
> OutOfRangeError (see above for traceback): RandomShuffleQueue '_4_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 10, current size 6) [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
你好，我和你遇到了一样的问题，请问您是怎么解决的呀？求指教

**Comment by lfxuan** [comment]
@chke097 建议检查数据加载和数据是否有错，或者注释掉“shuffle”。

**Comment by chke097** [comment]
您好呀！我在训练的过程中又遇到了另一个问题，不知道您训练的过程中是否遇到。作者给定的数据集的mr数据好像全部用于训练（9600）和验证（2400），我在反向测试mr的时候用作者给定测试集测试出现错误，不清楚作者的mr数据是哪部分用于训练和验证的呢？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月14日 10:32 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [cchen-cc/SIFA] assd error (#7) |

建议检查数据加载和数据是否有错，或者注释掉“shuffle”。
