### ISSUE TITLE
The pre-processing of the original data

### ISSUE THREAD

**Issue by chinacui** [cchen-cc/SIFA#9]
Hi, Cheng. Thanks for your work. Could you share the pre-processing code about processing the original data to npz file? Thanks,

**Comment by cchen-cc** [comment]
To convert .nii data to npz file, you can refer to [here](https://github.com/cchen-cc/SIFA/blob/master/utils/savenpz.py). 

The preprocessing steps can refer to [here](https://github.com/carrenD/Medical-Cross-Modality-Domain-Adaptation/issues/12).
